spring.profiles.active=${PROFILE:dev}

springdoc.swagger-ui.doc-expansion=none

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

rabbitmq.event-notification-exchange=event-notification-exchange
rabbitmq.event-notification-routing-key=event.notification.key
rabbitmq.event-notification-queue=event-notification-queue